export default {
  searchForm: document.getElementById('searchForm'),
  searchFormMobile: document.getElementById('searchFormMobile'),
  galleryBox: document.querySelector('.gallery__wrapper'),
  genreList: document.querySelector('.gallery__film-category__light'),
  bodyTheme: document.querySelector('body'),
  iconThemeDesktop: document.querySelector('.desktopSwitcher__toggle'),
  iconThemeMobile: document.querySelector('.themeSwitch__toggle'),
  cardModal: document.querySelector('.card__modal__lightbox'),
  cardOverlay: document.querySelector('.card__overlay'),
  cardBox: document.querySelector('.card__box'),
  preLoadPage: document.querySelector('.preloading-container'),
  topRatedBtn: document.querySelector('.topRatedBtn'),
  popularBtn: document.querySelector('.popularBtn'),
  upcomingBtn: document.querySelector('.upcomingBtn'),
  libraryList: document.querySelector('.library__list'),
  year: document.getElementById('year'),
  loginFormBackdrop: document.querySelector('.login-form__backdrop'),
  loginFormCloseButton: document.querySelector('.login-form__close-button'),
  loginFormOpenButton: document.querySelector('.authorization'),
  loginFormOpenButtonDesktop: document.querySelector('.desktopAuth'),
  signinBtn: document.getElementById('signinBtn'),
  signupBtn: document.getElementById('signupBtn'),
  regEmail: document.getElementById('regEmail'),
  regPass: document.getElementById('regPass'),
  signupEmail: document.getElementById('signupEmail'),
  signupPass: document.getElementById('signupPass')
};
