export default {
  searchForm: document.getElementById('searchForm'),
  searchFormMobile: document.getElementById('searchFormMobile'),
  galleryBox: document.querySelector('.gallery__wrapper'),
  genreList: document.querySelector('.gallery__film-category__light'),
  bodyTheme: document.querySelector('body'),
  iconThemeDesktop: document.querySelector('.desktopSwitcher__toggle'),
  iconThemeMobile: document.querySelector('.themeSwitch__toggle'),
  cardModal: document.querySelector('.card__modal__lightbox'),
  cardOverlay: document.querySelector('.card__overlay'),
  cardBox: document.querySelector('.card__box'),
  popularBtn: document.querySelector('.popularBtn'),
  latestBtn: document.querySelector('.latestBtn'),
  upcomingBtn: document.querySelector('.upcomingBtn'),
};
