export default {
  galleryBox: document.querySelector('.gallery__wrapper'),
  genreList: document.querySelector('.gallery__film-category__light'),
  bodyTheme: document.querySelector('body'),
  iconThemeDesktop: document.querySelector('.desktopSwitcher__toggle'),
  iconThemeMobile: document.querySelector('.themeSwitch__toggle'),
  cardModal: document.querySelector('.card__modal__lightbox'),
  cardOverlay: document.querySelector('.card__overlay'),
  cardBox: document.querySelector('.card__box'),
  preLoadPage: document.querySelector('.preloading-container'),
  topRatedBtn: document.querySelector('.topRatedBtn'),
  popularBtn: document.querySelector('.popularBtn'),
  upcomingBtn: document.querySelector('.upcomingBtn'),
  libraryList: document.querySelector('.library__list'),
  year: document.getElementById('year'),
  loginFormBackdrop: document.querySelector('.login-form__backdrop'),
  loginFormCloseButton: document.querySelector('.login-form__close-button'),
  loginFormOpenButton: document.querySelector('.authorization'),
  loginFormOpenButtonDesktop: document.querySelector('.desktopAuth'),
  
  // burger
  openMenuBtn: document.querySelector('.openBurgerMenu'),   closeMenuBtn: document.querySelector('.closeBurgerMenu'),  
  burger: document.querySelector('.modal'),
  menu: document.querySelector('.navBar'),
  switcher: document.querySelector('.burger-overlay'),
  
  // searching
  searchForm: document.getElementById('searchForm'),
  searchFormMobile: document.getElementById('searchFormMobile'),
  searchBtn: document.querySelector('.searchBtn'),
  mobileSearchBtn: document.querySelector('.mobileSearchBtn'),
  openInputBtn: document.querySelector('.openInputBtn'),
  closeInputBtn: document.querySelector('.closeInputBtn'),
  inputPanel: document.querySelector('.inputPanel'),

  // =====
  signinBtn: document.getElementById('signinBtn'),
  signupBtn: document.getElementById('signupBtn'),
  regEmail: document.getElementById('regEmail'),
  regPass: document.getElementById('regPass'),
  signupEmail: document.getElementById('signupEmail'),
  signupPass: document.getElementById('signupPass'),
  logoutBtn: document.getElementById('logoutBtn'),
  loginFields: document.getElementById('loginFields'),
  loginErrorMessage: document.querySelector('.login-form__error-message'),
  openInputBtn: document.querySelector('.openInputBtn'),
  emptyNotice: document.querySelector('.empty__notice'),
  welcomeMeassage: document.querySelector('.login-form__welcome-message'),
  libraryRef: document.getElementById('libraryRef'),
  libraryRefMobile: document.getElementById('libraryRefMobile')
};
